# Site settings
title: 的博客
email: dragonkingwhd@gmail.com
description: >-
  一个字：酷
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dragonkingwhd@gmail.com
github_username: dragonkingwhd@gmail.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "王哈哈"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Custom settings
show_excerpts: true
date_format: "%Y年%m月%d日"

# Navigation
navigation:
  - title: 首页
    url: /
  - title: 博客
    url: /blog/
  - title: 项目
    url: /projects/
  - title: 工具
    url: /tools/
  - title: 关于
    url: /about/

# Social links
social:
  github: dragonkingwhd@gmail.com
  twitter: dragonkingwhd@gmail.com
  email: dragonkingwhd@gmail.com
  linkedin: dragonkingwhd@gmail.com